[ipaserver]
ipa-server.lab.local
[ipaclients]
ym-client1.lab.local
ym-client2.lab.local
ym-client3.lab.local
[nfsserver]
ipa-server.lab.local # The IPA server also acts as NFS server in this lab
[lab:children]
ipaserver
ipaclients
