---
- name: Create IPA Users
  hosts: ipaserver
  vars_files:
    - /home/ansible/ansible-freeipa-nfs/group_vars/user_passwords.yml
    - /home/ansible/ansible-freeipa-nfs/group_vars/user_list.yml  

  tasks:
  
    - name: Create Users
      freeipa.ansible_freeipa.ipauser:
        name: "{{ item.username }}"
        first: "{{ item.first }}"
        last: "{{ item.last }}"
        password: "{{ item.password }}"
        homedir: "{{ item.homedirectory }}"
        state: present
      loop: "{{ users }}"

    - name: Create home directory on designated host
      ansible.builtin.file:
        path: /home/{{ item.username }}
        state: directory
        owner: "{{ item.username }}"
        group: "{{ item.username }}"
        mode: '0700'
      delegate_to: "{{ item.home_host }}"
      loop: "{{ users }}"
